import argparse
from pathlib import Path

from rgb565 import image_to_rgb565_array


def format_to_image_h(rgb565_array: list[int], width: int, height: int, var_name: str) -> str:
    bytes_list = []
    for color in rgb565_array:
        bytes_list.append(f"0x{color >> 8:02X}")
        bytes_list.append(f"0x{color & 0xFF:02X}")

    bytes_per_row = width * 2
    lines = [bytes_list[i:i + bytes_per_row] for i in range(0, len(bytes_list), bytes_per_row)]
    formatted = ",\n\t".join(", ".join(line) for line in lines)

    return f"""
const uint8_t raw_{var_name}[{len(rgb565_array) * 2}] PROGMEM = {{
\t{formatted}
}};

const Image565 image_{var_name} = {{ {width}, {height}, raw_{var_name} }};
"""


def main():
    parser = argparse.ArgumentParser(description="Convert images to RGB565 C header")
    parser.add_argument("--input", "-i", default=None, help="Input folder (default: img)")
    parser.add_argument("--output", "-o", default=None, help="Output file (default: source/images.h)")
    parser.add_argument("--pattern", "-p", default="*.png", help="Glob pattern (default: *.png)")
    args = parser.parse_args()

    base_path = Path(__file__).parent / ".."
    img_folder = Path(args.input) if args.input else (base_path / "img").resolve()
    output_file = Path(args.output) if args.output else (base_path / "source" / "images.h").resolve()

    images = sorted(img_folder.glob(args.pattern))

    if not images:
        print(f"No images found matching '{args.pattern}' in {img_folder}")
        return

    externs = "\n".join(f"extern const Image565 image_{p.stem};" for p in images)

    content = f"""// Auto-generated by tools/main.py.

#pragma once

#include "image565.h"

{externs}

#ifdef IMAGE565_IMAGES_IMPLEMENTATION
"""

    for img_path in images:
        print(f"Processing: {img_path.name}")
        array, w, h = image_to_rgb565_array(img_path)
        var_name = img_path.stem
        content += format_to_image_h(array, w, h, var_name)

    content += "\n#endif\n"

    output_file.parent.mkdir(parents=True, exist_ok=True)
    with open(output_file, "w") as f:
        f.write(content)

    print(f"Generated: {output_file} ({len(images)} images)")


if __name__ == "__main__":
    main()